keys:
  - &lucas age19842x4gme2mqjcayd0w4mq3szxyv939n97gw854gtn6mhdr0rcksv4vm3u
  - &sirocco age16nv73q9qrkzwgdyzztf65lhmrkqzjvs6ladt5cyqassy05xjc9nsmpa6d4
creation_rules:
  - path_regex: ^hosts/sirocco/secrets.yaml$
    key_groups:
      - age:
        - *lucas
        - *sirocco
