keys:
  - &lucas age19842x4gme2mqjcayd0w4mq3szxyv939n97gw854gtn6mhdr0rcksv4vm3u
  - &sirocco age16nv73q9qrkzwgdyzztf65lhmrkqzjvs6ladt5cyqassy05xjc9nsmpa6d4
  - &tramontane age1a0lxtqlp5wmplquat6ny0re4j37jstpzf6zrjpafg4zzvztt5f4qwpa4y9
creation_rules:
  - path_regex: ^hosts/sirocco/secrets.yaml$
    key_groups:
      - age:
        - *lucas
        - *sirocco
  - path_regex: ^hosts/tramontane/secrets.yaml$
    key_groups:
      - age:
        - *lucas
        - *tramontane
