---

- name: set up bise
  become: yes
  # roles: [system, navidrome, rtorrent, rutorrent, artis3n.tailscale]
  roles: [ rtorrent, rutorrent ]
  vars:
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"

    navidrome_version: 0.54.4
    navidrome_user: navidrome
    navidrome_group: navidrome

    navidrome_install_location: /opt

    navidrome_config_dir: /var/lib/navidrome
    navidrome_config_file: navidrome.toml
    navidrome_pid_file: /var/run/navidrome.pid
    navidrome_config:
      MusicFolder: /media/files
      DataFolder: "{{ navidrome_config_dir }}"
      AutoImportPlaylists: false
      Spotify.ID: "{{ lookup('env', 'SPOTIFY_ID') }}"
      Spotify.Secret: "{{ lookup('env', 'SPOTIFY_SECRET') }}"
      LastFM.ApiKey: "{{ lookup('env', 'LASTFM_APIKEY') }}"
      LastFM.Secret: "{{ lookup('env', 'LASTFM_SECRET') }}"

    rtorrent_user: rtorrent
    rtorrent_group: rtorrent
    rtorrent_directory_download: /media/files/
    rtorrent_directory_session: /var/lib/rtorrent/
    rtorrent_directory_config: /etc/rtorrent/
    rtorrent_directory_watch: /media/torrents/
    rtorrent_other_settings:
      - "scgi_port = 127.0.0.1:5000"

  hosts: bise



